import torch
import networkx as nx
import argparse
import os
import sys
import time

COMPOSITION_EDGE_TYPE_ID = 0  # Project-facing label: Type 1
TERM_LINK_EDGE_TYPE_ID = 1    # Project-facing label: Type 2
COMPOSITION_EDGE_LABEL = "Type 1"
TERM_LINK_EDGE_LABEL = "Type 2"


def reconstruct_terms(
    dataset_path,
    cutoff=5,
    shortest_only=False,
    predicted_only=False,
    include_predicted_negatives=False,
    composition_from_test=False,
    prediction_only_eval=False,
    output_path=None
):
    print(f"Loading dataset from {dataset_path}...")
    start_time = time.time()
    dataset = torch.load(dataset_path, weights_only=False)
    
    # データセットの構造確認と抽出
    # datasetは辞書形式で保存されている
    vocab = dataset['vocab']
    
    # Display optimal threshold if available
    if 'optimal_threshold' in dataset:
        print(f"Optimal threshold used for link prediction: {dataset['optimal_threshold']:.4f}")
    
    # 逆引き辞書 (ID -> Word)
    id_to_word = {v: k for k, v in vocab.items()}
    
    # エッジデータの取得
    # Case 1: trained_dataset.pt (フラット構造)
    if 'edge_index' in dataset and 'edge_type' in dataset:
        print("Detected trained_dataset format (flat structure).")
        full_edge_index = dataset['edge_index']
        full_edge_type = dataset['edge_type']
    
    # Case 2: processed_dataset.pt (階層構造)
    else:
        print("Detected processed_dataset format (nested structure).")
        # dataset['train']['pos_edge_index'] 等に分かれていると想定
        edge_indices = []
        edge_types = []
        
        for split in ['train', 'val', 'test']:
            if split in dataset:
                edge_indices.append(dataset[split]['pos_edge_index'])
                edge_types.append(dataset[split]['pos_edge_type'])
                
        if not edge_indices:
            print("Error: No edges found in dataset.")
            return

        full_edge_index = torch.cat(edge_indices, dim=1)
        full_edge_type = torch.cat(edge_types)
    
    print(f"Total edges: {full_edge_index.size(1)}")
    
    # Build the composition graph from Type 1 edges.
    # Internal id 0 is displayed as Type 1 in this project.
    G_comp = nx.DiGraph()
    
    # ノードを追加 (孤立点も含めるため)
    num_nodes = dataset['num_nodes']
    G_comp.add_nodes_from(range(num_nodes))
    
    if prediction_only_eval:
        print(f"Composition graph source: predicted edges only ({COMPOSITION_EDGE_LABEL})")
        composition_edges = []
        
        if 'predicted_test_edges' not in dataset or 'predicted_test_types' not in dataset:
            print("Error: 'predicted_test_edges' or 'predicted_test_types' not found in dataset.")
            print("Make sure you are using a trained_dataset.pt generated by the updated train.py.")
            return
        
        pred_pos_edges = dataset['predicted_test_edges']
        pred_pos_types = dataset['predicted_test_types']
        if pred_pos_edges.is_cuda:
            pred_pos_edges = pred_pos_edges.cpu()
        if pred_pos_types.is_cuda:
            pred_pos_types = pred_pos_types.cpu()
        
        pos_composition_mask = (pred_pos_types == COMPOSITION_EDGE_TYPE_ID)
        pos_composition_edges = pred_pos_edges[:, pos_composition_mask].t().tolist()
        composition_edges.extend(pos_composition_edges)
        print(f"  Predicted positive {COMPOSITION_EDGE_LABEL} edges: {len(pos_composition_edges)}")
        
        if 'predicted_test_neg_edges' in dataset and 'predicted_test_neg_types' in dataset:
            pred_neg_edges = dataset['predicted_test_neg_edges']
            pred_neg_types = dataset['predicted_test_neg_types']
            if pred_neg_edges.is_cuda:
                pred_neg_edges = pred_neg_edges.cpu()
            if pred_neg_types.is_cuda:
                pred_neg_types = pred_neg_types.cpu()
            
            neg_composition_mask = (pred_neg_types == COMPOSITION_EDGE_TYPE_ID)
            neg_composition_edges = pred_neg_edges[:, neg_composition_mask].t().tolist()
            composition_edges.extend(neg_composition_edges)
            print(f"  Predicted negative {COMPOSITION_EDGE_LABEL} edges (FP): {len(neg_composition_edges)}")
        else:
            print(f"  Note: predicted_test_neg_edges not found; using only predicted positive {COMPOSITION_EDGE_LABEL}.")
        
        print(f"  Total predicted {COMPOSITION_EDGE_LABEL} edges: {len(composition_edges)}")
        
    elif composition_from_test:
        print("Composition graph source: test split only")
        if 'test' in dataset:
            comp_edge_index = dataset['test']['pos_edge_index']
            comp_edge_type = dataset['test']['pos_edge_type']
        elif 'test_edges' in dataset and 'test_edge_types' in dataset:
            comp_edge_index = dataset['test_edges']
            comp_edge_type = dataset['test_edge_types']
        else:
            print("Error: test split edges not found; cannot use --composition_from_test.")
            return
        if comp_edge_index.is_cuda:
            comp_edge_index = comp_edge_index.cpu()
        if comp_edge_type.is_cuda:
            comp_edge_type = comp_edge_type.cpu()
        composition_mask = (comp_edge_type == COMPOSITION_EDGE_TYPE_ID)
        composition_edges = comp_edge_index[:, composition_mask].t().tolist()
        if 'predicted_test_neg_edges' in dataset and 'predicted_test_neg_types' in dataset:
            pred_neg_edges = dataset['predicted_test_neg_edges']
            pred_neg_types = dataset['predicted_test_neg_types']
            if pred_neg_edges.is_cuda:
                pred_neg_edges = pred_neg_edges.cpu()
            if pred_neg_types.is_cuda:
                pred_neg_types = pred_neg_types.cpu()
            neg_composition_mask = (pred_neg_types == COMPOSITION_EDGE_TYPE_ID)
            neg_composition_edges = pred_neg_edges[:, neg_composition_mask].t().tolist()
            if neg_composition_edges:
                composition_edges.extend(neg_composition_edges)
                print(f"Included {len(neg_composition_edges)} predicted negative {COMPOSITION_EDGE_LABEL} edges (score > 0.5).")
        else:
            print(f"Note: predicted negative edges not found; using only test positive {COMPOSITION_EDGE_LABEL} edges.")
    else:
        composition_mask = (full_edge_type == COMPOSITION_EDGE_TYPE_ID)
        composition_edges = full_edge_index[:, composition_mask].t().tolist()
    G_comp.add_edges_from(composition_edges)
    
    print(f"Composition graph built. Nodes: {G_comp.number_of_nodes()}, Edges: {G_comp.number_of_edges()}")
    
    # Type 2 term links provide the source/target pairs to reconstruct.
    # Internal id 1 is displayed as Type 2 in this project.
    term_link_edges = []
    
    if prediction_only_eval:
        print(f"Term link source: predicted edges only ({TERM_LINK_EDGE_LABEL})")
        
        if 'predicted_test_edges' not in dataset or 'predicted_test_types' not in dataset:
            print("Error: 'predicted_test_edges' or 'predicted_test_types' not found in dataset.")
            print("Make sure you are using a trained_dataset.pt generated by the updated train.py.")
            return
        
        pred_pos_edges = dataset['predicted_test_edges']
        pred_pos_types = dataset['predicted_test_types']
        if pred_pos_edges.is_cuda:
            pred_pos_edges = pred_pos_edges.cpu()
        if pred_pos_types.is_cuda:
            pred_pos_types = pred_pos_types.cpu()
        
        pos_term_link_mask = (pred_pos_types == TERM_LINK_EDGE_TYPE_ID)
        pos_term_link_edges = pred_pos_edges[:, pos_term_link_mask].t().tolist()
        term_link_edges.extend(pos_term_link_edges)
        print(f"  Predicted positive {TERM_LINK_EDGE_LABEL} edges: {len(pos_term_link_edges)}")
        
        if 'predicted_test_neg_edges' in dataset and 'predicted_test_neg_types' in dataset:
            pred_neg_edges = dataset['predicted_test_neg_edges']
            pred_neg_types = dataset['predicted_test_neg_types']
            if pred_neg_edges.is_cuda:
                pred_neg_edges = pred_neg_edges.cpu()
            if pred_neg_types.is_cuda:
                pred_neg_types = pred_neg_types.cpu()
            
            neg_term_link_mask = (pred_neg_types == TERM_LINK_EDGE_TYPE_ID)
            neg_term_link_edges = pred_neg_edges[:, neg_term_link_mask].t().tolist()
            term_link_edges.extend(neg_term_link_edges)
            print(f"  Predicted negative {TERM_LINK_EDGE_LABEL} edges (FP): {len(neg_term_link_edges)}")
        else:
            print(f"  Note: predicted_test_neg_edges not found; using only predicted positive {TERM_LINK_EDGE_LABEL}.")
        
        print(f"  Total predicted {TERM_LINK_EDGE_LABEL} edges: {len(term_link_edges)}")
        
    elif predicted_only:
        print("Mode: predicted_only=True")
        if 'predicted_test_edges' in dataset:
            # Use predicted edges stored in trained_dataset.pt.
            pred_edges = dataset['predicted_test_edges']
            pred_types = dataset.get('predicted_test_types', None)
            
            if pred_types is not None:
                if pred_edges.is_cuda:
                    pred_edges = pred_edges.cpu()
                if pred_types.is_cuda:
                    pred_types = pred_types.cpu()
                pos_term_link_mask = (pred_types == TERM_LINK_EDGE_TYPE_ID)
                term_link_edges = pred_edges[:, pos_term_link_mask].t().tolist()
                print(f"  Filtered to {TERM_LINK_EDGE_LABEL} only: {len(term_link_edges)} edges")
            else:
                # Backward compatibility: old files may not store predicted types.
                term_link_edges = pred_edges.t().tolist()
            
            pred_pos_count = len(term_link_edges)
            pred_neg_count = 0
            
            if include_predicted_negatives:
                if 'predicted_test_neg_edges' in dataset:
                    pred_neg_edges = dataset['predicted_test_neg_edges']
                    pred_neg_types = dataset.get('predicted_test_neg_types', None)
                    
                    if pred_neg_edges.is_cuda:
                        pred_neg_edges = pred_neg_edges.cpu()
                    
                    if pred_neg_types is not None:
                        if pred_neg_types.is_cuda:
                            pred_neg_types = pred_neg_types.cpu()
                        neg_term_link_mask = (pred_neg_types == TERM_LINK_EDGE_TYPE_ID)
                        neg_term_link_edges = pred_neg_edges[:, neg_term_link_mask].t().tolist()
                        pred_neg_count = len(neg_term_link_edges)
                        term_link_edges.extend(neg_term_link_edges)
                    else:
                        # Backward compatibility: old files may not store predicted types.
                        pred_neg_count = pred_neg_edges.size(1)
                        term_link_edges.extend(pred_neg_edges.t().tolist())
                else:
                    print("Error: 'predicted_test_neg_edges' not found in dataset. Cannot use --include_predicted_negatives.")
                    print("Make sure you are using a trained_dataset.pt generated by the updated train.py.")
                    return
            if include_predicted_negatives:
                print(f"Using {pred_pos_count} predicted positive {TERM_LINK_EDGE_LABEL} edges and {pred_neg_count} predicted negative {TERM_LINK_EDGE_LABEL} edges as targets.")
            else:
                print(f"Using {pred_pos_count} predicted {TERM_LINK_EDGE_LABEL} edges as targets.")
        else:
            print("Error: 'predicted_test_edges' not found in dataset. Cannot use --predicted_only.")
            print("Make sure you are using a trained_dataset.pt generated by the updated train.py.")
            return
    else:
        term_link_mask = (full_edge_type == TERM_LINK_EDGE_TYPE_ID)
        term_link_edges = full_edge_index[:, term_link_mask].t().tolist()
    
    total_pairs = len(term_link_edges)
    print(f"Found {total_pairs} term links ({TERM_LINK_EDGE_LABEL} links) to reconstruct. Starting reconstruction...")
    print(f"Configuration: cutoff={cutoff}, shortest_only={shortest_only}")
    
    reconstructed_terms = set()
    process_start_time = time.time()
    
    for idx, (src, dst) in enumerate(term_link_edges):
        if idx > 0 and idx % 100 == 0:
            elapsed = time.time() - process_start_time
            avg_time = elapsed / idx
            remaining = (total_pairs - idx) * avg_time
            print(f"Processed {idx}/{total_pairs} pairs. Elapsed: {elapsed:.2f}s. Estimated remaining: {remaining:.2f}s")

        # src == dst の場合（1単語の用語）はパス探索不要だが、
        # "shortest path"系関数は src==dst の場合 [src] を返すのでそのまま使える場合もある。
        
        if src == dst:
            word = id_to_word[src]
            reconstructed_terms.add(word)
            continue
            
        try:
            if shortest_only:
                # 最短パスのみ探索 (高速)
                path = nx.shortest_path(G_comp, source=src, target=dst)
                words = [id_to_word[node_id] for node_id in path]
                term = " ".join(words)
                reconstructed_terms.add(term)
            else:
                # 全単純パス探索 (遅い可能性あり)
                paths = nx.all_simple_paths(G_comp, source=src, target=dst, cutoff=cutoff)
                for path in paths:
                    words = [id_to_word[node_id] for node_id in path]
                    term = " ".join(words)
                    reconstructed_terms.add(term)
                
        except nx.NetworkXNoPath:
            continue
            
    total_elapsed = time.time() - start_time
    print(f"\nReconstruction finished in {total_elapsed:.2f} seconds.")
    print(f"Reconstructed {len(reconstructed_terms)} unique terms.")
    
    # 結果を表示（または保存）
    sorted_terms = sorted(list(reconstructed_terms))
    
    # Determine output path
    if output_path is None:
        dataset_dir = os.path.basename(os.path.dirname(dataset_path)) or "dataset"
        output_name = f"{dataset_dir}_reconstruct_terms.txt"
        repo_root = os.path.dirname(os.path.abspath(__file__))
        output_dir = os.path.join(os.path.dirname(repo_root), 'results', 'reconstruct_terms')
        os.makedirs(output_dir, exist_ok=True)
        output_file = os.path.join(output_dir, output_name)
    else:
        output_file = output_path
        os.makedirs(os.path.dirname(output_file) or '.', exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        for term in sorted_terms:
            f.write(term + '\n')
            
    print(f"Terms saved to {output_file}")
    
    # 一部を表示
    print("\nSample reconstructed terms:")
    for term in sorted_terms[:10]:
        print(f"- {term}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Reconstruct terms from RGNN graph')
    parser.add_argument('--dataset_path', type=str, default='./RGNN/data/processed_dataset.pt', 
                        help='Path to processed dataset (.pt)')
    parser.add_argument('--cutoff', type=int, default=5, help='Max path length for term reconstruction')
    parser.add_argument('--shortest_only', action='store_true', help='Find only shortest paths (faster)')
    parser.add_argument('--predicted_only', action='store_true', help='Reconstruct only links predicted in test set (requires trained_dataset.pt)')
    parser.add_argument('--include_predicted_negatives', action='store_true', help='Include negative test samples with score > 0.5 (requires trained_dataset.pt)')
    parser.add_argument('--composition_from_test', action='store_true', help='Build composition graph using only test split Type 1 edges')
    parser.add_argument('--prediction_only_eval', action='store_true', 
                        help='Use ONLY predicted edges for both composition (Type 1) and term links (Type 2). '
                             'This enables pure prediction-based evaluation. (requires trained_dataset.pt)')
    parser.add_argument('--output_path', type=str, default=None, help='Output path for reconstructed terms (default: auto-generate)')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.dataset_path):
        print(f"Error: File not found at {args.dataset_path}")
        sys.exit(1)
        
    reconstruct_terms(
        args.dataset_path,
        cutoff=args.cutoff,
        shortest_only=args.shortest_only,
        predicted_only=args.predicted_only,
        include_predicted_negatives=args.include_predicted_negatives,
        composition_from_test=args.composition_from_test,
        prediction_only_eval=args.prediction_only_eval,
        output_path=args.output_path
    )

